version: '3.8'
services:
  nginx:
    image: nginx:wizard
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
    - 80:80
    restart: always
    networks:
    - fe_service
  jenkins:
    image: jenkins:wizard
    container_name: jenkins
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
    - 8080:8080
    restart: always
    networks:
    - fe_service
networks:
  fe_service:
    driver: bridge
    name: fe_service
